services:
  db:
    image: postgres:15
    env_file:
      - .env
    container_name: shorturl-db
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: shorturl-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_URL}
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    restart: always

volumes:
  db_data:
    driver: local